### ISSUE TITLE
websocket监听comfyui事件类型有误

### ISSUE THREAD

**Issue by Arthur-xu** [bobvinch/comfy-server#6]
根据comfyui官方文档，似乎应该监听事件类型是execting并且node节点为null的时候才代表job执行完毕。
https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py#L36C25-L36C29
这里监听executed是有其他原因吗?
https://github.com/bobvinch/comfy-server/blob/master/src/draw/DrawCosumer.ts#L91C27-L91C35

**Comment by bobvinch** [comment]
excuted这个节点的时候已经产出了，节点None的情况很多，不一定都是任务结束
