### ISSUE TITLE
有没有获取工作流id和链接的接口？

### ISSUE THREAD

**Issue by a568640533** [bobvinch/comfy-server#7]

**Comment by bobvinch** [comment]
有的，工作流按照用户保存的，按照用户id和名字取获取，这样可以方便后续做工作流分享，也更加符合面向对象













在 2024-05-26 10:00:18，"a568640533" ***@***.***> 写道：

**Comment by a568640533** [comment]
好的，多谢 晚上拉取 运行看看 有问题我在请教
