### ISSUE TITLE
使用非容器方式可以运行吗？

### ISSUE THREAD

**Issue by jueming0312** [bobvinch/comfy-server#8]
请问这个项目涉及到的数据库程序是否可以全部运行在同一个容器中。有交流群吗是否可以加群?

**Comment by bobvinch** [comment]
可以的
















在 2024-08-03 10:36:51，"Justroy" ***@***.***> 写道：

请问这个项目涉及到的数据库程序是否可以全部运行在同一个容器中。有交流群吗是否可以加群?

**Comment by bobvinch** [comment]
已支持
